add authorization doc
devonfw/architectures pull request #21
Opened 2021-07-16 08:31 UTC by lilliCao

Resolves #11

2021-07-20 09:03 UTC, SchettlerKoehler requested changes

2021-07-20 09:03 UTC, SchettlerKoehler commented on solutions/authorization/index.asciidoc
> +
Do not use the pattern that no configured permissions mean the user has all permissions

2021-07-21 06:31 UTC, lilliCao commented on solutions/authorization/index.asciidoc
> +|Permission|A permission is an object that allows a principal to perform an operation in the system. This permission can be _granted_ (give) or _revoked_ (taken away). Sometimes people also use the t
|Pricipal| A user or application that can authenticate itself?

2021-07-21 06:32 UTC, lilliCao commented on solutions/authorization/index.asciidoc
> +[options="header", cols="15%,85%"]
I think the table is fine

2021-07-21 08:13 UTC, SchettlerKoehler commented on solutions/authorization/index.asciidoc
> +|Permission|A permission is an object that allows a principal to perform an operation in the system. This permission can be _granted_ (give) or _revoked_ (taken away). Sometimes people also use the t
https://en.wikipedia.org/wiki/Principal_(computer_security)

2021-07-29 06:46 UTC, SchettlerKoehler approved these changes

2021-07-29 06:47 UTC, merged